### ISSUE TITLE
fs__default is not defined

### ISSUE THREAD

**Issue by calvbore** [briangu33/circom-starter#2]
So `yarn dev` seems not to work on windows, I'm assuming this is because snarkjs doesn't play very well with windows, haven't had a chance to test on  a linux machine yet.

<img width="358" alt="circom-starter-error" src="https://user-images.githubusercontent.com/47094796/107611066-c1174d00-6c08-11eb-87c1-795bac69620c.PNG">

**Comment by jacobrosenthal** [comment]
Thanks for the report. I can confirm upstream with snark 3.5.1 in the lock file, as well as 3.5.9 (the latest snarkjs) both work on linux so it does appear to be a windows thing with that rollup fs__ stuff. @phated has been looking at snarkjs a ton recently so hoping he can weigh in.

**Comment by phated** [comment]
It seems that you are also on a really old version of nodejs. Basically, snarkjs only commits to working on node 14+ (though you can force it to work on 12-something). If you are using node 14+, it will load the ESM modules, which wouldn't show this issue.
